apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: platform
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: identity
          image: platform/identity:dev # PENDIENTE: publicar imagen en registry
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secrets
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 768Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: platform
  labels:
    app: identity
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - name: http
      port: 8081
      targetPort: 8081
